version: "3.3"
services:
    nginx:
        image: nginx:latest
        volumes:
            - ./cpan.site:/etc/nginx/conf.d/default.conf
            - cpan:/opt/cpan
    cpan-mini:
        image: cpanmini:latest
        build: .
        volumes:
            - cpan:/opt/cpan/minicpan
volumes:
    cpan:
# volume group?
# FIXME: how do we update the mirror?

